project_id = "xnncvfuamecmjvvoaywz"

[functions.coach-chat]
verify_jwt = false

[functions.deepgram-stt]
verify_jwt = false

[functions.deepgram-tts]
verify_jwt = false

[functions.deepgram-tts-stream]
verify_jwt = false

[functions.cartesia-tts-stream]
verify_jwt = false

[functions.menu-parse]
verify_jwt = false

[functions.meal-analyze]
verify_jwt = false