// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnncvfuamecmjvvoaywz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhubmN2ZnVhbWVjbWp2dm9heXd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NDkwMzUsImV4cCI6MjA3MjAyNTAzNX0.mJttLdAFIT0nFDGF3cj1mBYhqy5o7xUMUSfePILllGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});